---
- name: Clone dotfiles repo
  ansible.builtin.git:
    repo: https://github.com/aairey/dotfiles
    accept_hostkey: true
    dest: '~/dotfiles/'
    version: master
    force: true
  changed_when: false

- name: Install dotdrop dependencies
  ansible.builtin.pip:
    requirements: '~/dotfiles/dotdrop/requirements.txt'
    extra_args: '--user'
  tags:
    - molecule-idempotence-notest

- name: Bootstrap dotdrop and install dotfiles using dotdrop
  ansible.builtin.shell: |
    dotdrop/bootstrap.sh
    ./dotdrop.sh --cfg=./dotdrop.yml install -f
  args:
    chdir: '~/dotfiles'
  tags:
    # bug in older versions of python and pip
    # https://github.com/ansible/ansible/issues/28952
    - skip_ansible_lint
    - molecule-idempotence-notest
  register: dotdrop_bootstrap
  failed_when: dotdrop_bootstrap.rc >= 2
  changed_when: dotdrop_bootstrap.rc != 0

- name: Change shell to zsh
  ansible.builtin.command: "/usr/bin/chsh -s /usr/bin/zsh {{ ansible_user_id }}"
  become: yes
  tags:
    - skip_ansible_lint
  changed_when: false
