---
- name: Install colorls globally on Debian 10
  become: true
  community.general.gem:
    name: colorls
    state: present
    version: 1.4.4
    user_install: false
  when: ansible_distribution == 'Debian' and ansible_distribution_version == '10'

- name: Install colorls globally
  become: true
  community.general.gem:
    name: colorls
    state: present
    user_install: false
  when: not ansible_distribution == 'Debian' and ansible_distribution_version == '10'

- name: Update pip to latest version
  ansible.builtin.pip:
    name: pip
    state: latest
    executable: pip3
    extra_args: '--user'
  tags:
    - skip_ansible_lint
    - molecule-idempotence-notest

- name: Install requests
  ansible.builtin.pip:
    name: requests
    state: present
    executable: pip3
    extra_args: '--user'

- name: Install psutil
  ansible.builtin.pip:
    name: psutil
    state: present
    executable: pip3
    extra_args: '--user'

- name: Install virtualenvwrapper
  ansible.builtin.pip:
    name: virtualenvwrapper
    state: present
    executable: pip3
    extra_args: '--user'

- name: Install howdoi on CentOS 7
  ansible.builtin.pip:
    name: howdoi<2.0
    state: present
    executable: pip3
    extra_args: '--user'
  when: ansible_distribution == 'CentOS' and ansible_distribution_version == '7'
    
- name: Install howdoi
  ansible.builtin.pip:
    name: howdoi
    state: present
    executable: pip3
    extra_args: '--user'
  when: not ansible_distribution == 'CentOS' and ansible_distribution_version == '7'

- name: Install powerline-status globally
  become: true
  ansible.builtin.pip:
    name: powerline-status
    state: present
    executable: pip3
