---
# tasks file for aairey.os-base
- name: Include tasks for RedHat based systems
  ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Include tasks for Debian based systems
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install tools that shell relies on after setting dotfiles
  ansible.builtin.include_tasks: dotfiles-deps.yml

- name: Install dotfiles
  ansible.builtin.include_tasks: dotfiles.yml
