---
# tasks file for aairey.os-base
- ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- ansible.builtin.include_tasks: dotfiles-deps.yml

- ansible.builtin.include_tasks: dotfiles.yml
