---
# tasks file for aairey.dotfiles
- name: Install Packages
  become: true
  package:
    name: "{{ redhat_packages }}"
    state: present

- name: Install colorls
  become: true
  gem:
    name: colorls
    state: present
    user_install: false

- name: Install howdoi
  become: true
  pip:
    name: howdoi
    state: present
    executable: pip3

- name: Clone dotfiles repo
  git:
    repo: https://github.com/aairey/dotfiles
    accept_hostkey: true
    dest: '~/dotfiles/'
    version: master
    force: true
  register: clone_dotfiles
  changed_when: false

- name: Install dotdrop dependencies
  pip:
    requirements: '~/dotfiles/dotdrop/requirements.txt'
    executable: pip3
    extra_args: '--user'

- name: Bootstrap dotdrop and install dotfiles using dotdrop
  shell: |
    dotdrop/bootstrap.sh
    ./dotdrop.sh --cfg=./dotdrop.yml install
  args:
    chdir: '~/dotfiles'
  tags:
    - skip_ansible_lint
  register: dotdrop_bootstrap
  failed_when: dotdrop_bootstrap.rc >= 2
  changed_when: false
  when: clone_dotfiles.changed

- name: TODO change shell to zsh
  command: 'chsh -s /usr/bin/zsh'
  tags:
    - skip_ansible_lint
  changed_when: false
