---
# tasks file for aairey.dotfiles

- name: Install the EPEL repository
  become: true
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == 'CentOS'

- name: Install Packages
  become: true
  package:
    name: "{{ redhat_packages + common_packages }}"
    state: present
  retries: 5
  delay: 2
  register: redhat_packages_installation
  until: redhat_packages_installation is succeeded

- name: Extra Packages on Fedora
  become: true
  dnf:
    name: "{{ fedora_packages }}"
    state: present
  when: ansible_distribution == 'Fedora'
