---
# tasks file for aairey.dotfiles
- name: Install Packages
  become: true
  package:
    name: "{{ redhat_packages }}"
    state: present
  retries: 5
  delay: 2
  register: redhat_packages
  until: redhat_packages is succeeded
