---
# tasks file for aairey.dotfiles

- name: Install the EPEL repository
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
  when: ansible_distribution == 'CentOS'

- name: Enable EPEL repository
  become: true
  ansible.builtin.command: amazon-linux-extras install epel -y
  tags:
    - skip_ansible_lint
  when: ansible_distribution == 'Amazon'

- name: Install Packages
  become: true
  ansible.builtin.package:
    name: "{{ redhat_packages + common_packages }}"
    state: present
  retries: 5
  delay: 2
  register: redhat_packages_installation
  until: redhat_packages_installation is succeeded

- name: Extra Packages on Fedora
  become: true
  ansible.builtin.dnf:
    name: "{{ fedora_packages }}"
    state: present
  when: ansible_distribution == 'Fedora'

- name: Extra Packages on Amazon Linux
  become: true
  ansible.builtin.yum:
    name: "{{ amazon_packages }}"
    state: present
  when: ansible_distribution == 'Amazon'
