---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8
driver:
  name: podman
platforms:
  - name: ${MOLECULE_DISTRO:-fedora33}
    image: docker.io/geerlingguy/docker-${MOLECULE_DISTRO:-fedora33}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks, timer
      stdout_callback: yaml
verifier:
  name: ansible
