---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
# unfortunately this scans everything including public collections pulled in
# lint: |
#   set -e
#   yamllint .
#   ansible-lint .
#   flake8
driver:
  name: podman
platforms:
  - name: ${MOLECULE_DISTRO:-fedora33}-${TOX_ENVNAME:-notox}
    image: docker.io/geerlingguy/docker-${MOLECULE_DISTRO:-fedora33}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_enabled: profile_tasks, timer, yaml
    ssh_connection:
        pipelining: False # Fixes bug on github-actions, see https://github.com/ansible-community/molecule-podman/issues/2
verifier:
  name: ansible
