---
- name: Prepare
  hosts: all
  tasks:
    - name: Make sure .ssh directory exists
      file:
        path: '~/.ssh'
        state: directory
        mode: '0700'
    - name: Copy SSH key for git checkout test
      copy:
        src: "~/.ssh/id_ed25519"
        dest: "~/.ssh/id_ed25519"
        mode: '0600'
    - name: 'Install curl on Ubuntu, needed by vivid install script'
      package:
        name: curl
        state: present
      when: ansible_distribution == 'Ubuntu'
