---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 0"

defaults:
  run:
    working-directory: "aairey.dotfiles"

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: "aairey.dotfiles"

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible ansible-lint flake8

      - name: Lint code.
        run: |
          yamllint .
          ansible-lint .
          flake8

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
        ansible-version:
          - "5"
          - "6"
        distro:
          - fedora35
          - fedora36
          - centos7
          - ubuntu1804
          - ubuntu2004
          - ubuntu2204
          - debian10

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: "aairey.dotfiles"

      - name: Set up Python.
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies.
        run: |
          python -m pip install --upgrade pip
          pip install -r test_requirements.txt
      
      - name: Add SSH deploy key for git tasks
        run: |
          mkdir ~/.ssh
          echo -e "${{ secrets.MOLECULE_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_ed25519

      - name: Run Molecule tests.
        run: tox
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_VERSION: ${{ matrix.ansible-version }}
          MOLECULE_DISTRO: ${{ matrix.distro }}
